name: flutter_integration_test_example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  auto_route: ^9.3.0+1
  clock: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_integration_test:
    path: ../
  build_runner: ^2.4.15
  auto_route_generator: ^9.3.1

flutter:
  uses-material-design: true
