name: flutter_integration_test
description: "Flutter integration tests"
version: 1.0.0
homepage:

environment:
  sdk: ^3.6.2
  flutter: ">=3.27.4"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  clock: ^1.1.1
  meta: ^1.15.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
